FROM php:8-apache-bookworm

ENV DEBIAN_FRONTEND noninteractive
ENV SHELL /bin/bash


ENV ALLOW_OVERWRITE=on \
    ANONYMOUS_DISABLE=off \
    ANON_UPLOAD_ENABLE=DenyAll \
    FTPUSER_PASSWORD_SECRET=ftp-user-password-secret \
    FTPUSER_NAME=ftpuser \
    FTPUSER_UID=1001 \
    LOCAL_UMASK=022 \
    MAX_CLIENTS=10 \
    MAX_INSTANCES=30 \
    PASV_ADDRESS= \
    PASV_MAX_PORT=30100 \
    PASV_MIN_PORT=30091 \
    SERVER_NAME=ProFTPD \
    TIMES_GMT=off \
    TZ=UTC \
    WRITE_ENABLE=AllowAll
RUN apt-get update
RUN apt-get install software-properties-common
RUN apt-get install --reinstall ca-certificates
RUN  add-apt-repository -y 'ppa:ondrej/apache2' && apt-get update
#required dependencies
RUN apt-get update 
RUN apt-get -y install --no-install-recommends tzdata locales \
    libfreetype6-dev libjpeg62-turbo-dev libmcrypt-dev libpng-dev zlib1g-dev net-tools \
    libxml2-dev libzip-dev libonig-dev graphviz openssl xinetd supervisor
#proftp and modules
RUN apt-get -y install proftpd-basic proftpd-mod-crypto  proftpd-mod-vroot 
	
#sqlite support
RUN apt-get install -y sqlite3 libsqlite3-dev  proftpd-mod-sqlite libsqlite3-0 
RUN apt-get install php8.2-sqlite3
RUN mkdir /sqlite_db
#create database and tables
COPY ./install/tables-sqlite3.sql /sqlite_db/sqlite_install_tables.sql
RUN /usr/bin/sqlite3 "/sqlite_db/ftpadmin.db < /sqlite_db/sqlite_install_tables.sql"


#cleanup
RUN apt-get clean \
    && rm -rf /var/lib/apt/lists/* /tmp/* /var/tmp/* /var/cache/apt/archive/*.deb
	

RUN ln -s "$PHP_INI_DIR/php.ini-production" "$PHP_INI_DIR/php.ini" 
RUN  a2enmod rewrite headers 
RUN  phpenmod pdo_sqlite
RUN  docker-php-ext-configure gd 
RUN  docker-php-ext-install gd zip 
RUN  docker-php-source delete 
RUN mkdir /var/www/html/proftpdadmin
COPY ./html /var/www/html/proftpdadmin

RUN  chown -R www-data:www-data /var/www/html 

COPY ./Docker/SQLite/sql.conf /etc/proftpd/sql.conf
COPY ./Docker/SQLite/modules.conf /etc/proftpd/modules.conf

# Do we actually *need this* ??
#20240501 Itseems we do, but I will just use the Debian package
# https://docs.docker.com/config/containers/multi-service_container/
# https://github.com/ochinchina/supervisord
#COPY --from=ochinchina/supervisord:latest /usr/local/bin/supervisord /usr/local/bin/supervisord
#RUN  mkdir -p /etc/supervisord
COPY ./Docker/supervisord/supervisord.conf /etc/
COPY ./Docker/supervisord/proftpd.conf /etc/supervisord/
RUN sed -i 's|set -e|set -e\n/usr/local/bin/supervisord --daemon -c /etc/supervisord.conf \&|' /usr/local/bin/docker-php-entrypoint


EXPOSE 20 21 $PASV_MIN_PORT-$PASV_MAX_PORT

