version: '3'
services:

  #docker-compose build --no-cache
  #docker-compose up -d
  #docker-compose exec mariadb bash -c "mysql -u root -h mariadb --password=root proftpd < /dump/tables.sql"

  #Apache Service + ProFTPD Service
  webserver:
    build:
      context: .
      dockerfile: SQLite/Dockerfile
    image: jniltinho/php8-apache
    container_name: webserver
    restart: unless-stopped
    tty: true
    ports:
      - "8080:80"
      - "20:20"
      - "21:21"
      - "60000-60100:60000-60100"
    volumes:
      - ./html:/var/www/html
      - ./proftpd.conf:/etc/proftpd/proftpd.conf
      - ./data/ftp:/srv/ftp
