version: '3'



services:
  #Apache Service + ProFTPD Service
  webserver:
    build:
      context: https://github.com/Ronaldvr/ProFTPd-Admin-SQLite.git
      dockerfile: Dockerfile.sqlite
    image: proftpd/contain
    container_name: proftpd_Adm
    restart: unless-stopped
    ports:
      - 8080:80
      - 20:20
      - 21:21
      - $PASV_MIN_PORT-$PASV_MAX_PORT:${PASV_MIN_PORT}-${PASV_MAX_PORT}
    volumes:
      - ./config/config.php:/var/www/html/proftpdadmin/configs/config.php
      - ./config/server.key:/etc/ssh/ssh_host_rsa_key:ro
      - ./config/server.key:/usr/local/proftpd/etc/proftpd.key.pem:ro
      - ./config/ftp.vanraay.org.pem:/usr/local/proftpd/etc/proftpd.cert.pem:ro
      - ./config/proftpd.conf:/etc/proftpd/proftpd.conf
      - ./config/sql.conf:/etc/proftpd/sql.conf
      - ./config/modules.conf:/etc/proftpd/modules.conf
      - ./logs/:/var/log/proftpd/
      - ./data/ftp:/srv/ftp
