version: '3'

name: w_proftpd_admin

services:
  #Apache Service + ProFTPD Service
  webserver:
    build:
      context: https://github.com/Ronaldvr/ProFTPd-Admin-SQLite.git
      dockerfile: Dockerfile.sqlite
#    image: proftpd/contain
    container_name: proftpd_Adm
    restart: unless-stopped
    env_file:
      - ./.env
    environment:
    - PFBLOWFISH=XXXXXXXX
#      - PFBLOWFISH='Ue]Ux:x[0343bUQNG5qEO'
    ports:
      - 8080:80
      - 20:20
      - 21:21
      - 22:22
      - 210:210
      - 211:211
      - 1023:1023
      - 1024:1024
      - $PASV_MIN_PORT-$PASV_MAX_PORT:${PASV_MIN_PORT}-${PASV_MAX_PORT}
    volumes:
      - ./config/config.ini:/var/www/html/proftpdadmin/configs/config.ini
      - ./config/server.key:/etc/ssh/ssh_host_rsa_key
      - ./config/server.key:/usr/local/proftpd/etc/proftpd.key.pem:ro
      - ./config/ftp.vanraay.org.pem:/usr/local/proftpd/etc/proftpd.cert.pem:ro
      - ./config/proftpd.conf:/etc/proftpd/proftpd.conf
      - ./config/sql.conf:/etc/proftpd/sql.conf
      - ./config/modules.conf:/etc/proftpd/modules.conf
      - ./logs/supervisord/:/var/log/supervisor/
      - ./logs/:/var/log/proftpd/
      - ./data/ftp:/srv/ftp
      - ./phpinfo:/var/www/html/phpinfo
      - /etc/passwd:/var/www/hostpasswd:ro
      - ./www/:/var/www/html/proftpdadmin/
      - ./db/:/var/www/html/proftpdadmin/db/
      
      
